In [1]:
import numpy as np

In [2]:
arr=np.array([[30,17,15],[19,90,16],[69,53,21]])
arr

array([[30, 17, 15],
       [19, 90, 16],
       [69, 53, 21]])

In [3]:
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[19 17 15]
 [30 53 16]
 [69 90 21]]
[[15 17 30]
 [16 19 90]
 [21 53 69]]


In [4]:
dt=np.dtype([('name','S10'),('age',int)])
arr=np.array([("karan",21),("Arpita",25),("ashish",17),("sam",27),("robin",22)],dtype=dt)
arr

array([(b'karan', 21), (b'Arpita', 25), (b'ashish', 17), (b'sam', 27),
       (b'robin', 22)], dtype=[('name', 'S10'), ('age', '<i4')])

In [5]:
np.sort(arr,order='name')

array([(b'Arpita', 25), (b'ashish', 17), (b'karan', 21), (b'robin', 22),
       (b'sam', 27)], dtype=[('name', 'S10'), ('age', '<i4')])

In [6]:
np.sort(arr,order='age')

array([(b'ashish', 17), (b'karan', 21), (b'robin', 22), (b'Arpita', 25),
       (b'sam', 27)], dtype=[('name', 'S10'), ('age', '<i4')])

In [7]:
arr=np.random.rand(5,5)
arr

array([[0.55819621, 0.73315878, 0.42576012, 0.59963178, 0.03497777],
       [0.76706165, 0.07550043, 0.9530925 , 0.85630328, 0.38878434],
       [0.69733079, 0.21435357, 0.8161581 , 0.7829357 , 0.26755666],
       [0.596787  , 0.08038642, 0.85611976, 0.37864073, 0.20463603],
       [0.91093024, 0.82338672, 0.18970325, 0.00893467, 0.44509906]])

In [8]:
print(np.argsort(arr,axis=0))

[[0 1 4 4 0]
 [3 3 0 3 3]
 [2 2 2 0 2]
 [1 0 3 2 1]
 [4 4 1 1 4]]


In [9]:
print(np.argsort(arr,axis=1))

[[4 2 0 3 1]
 [1 4 0 3 2]
 [1 4 0 3 2]
 [1 4 3 0 2]
 [3 2 4 1 0]]


In [10]:
print(np.argsort(arr,axis=None))

[23  4  6 16 22 19 11 14 18  9  2 24  0 15  3 10  1  5 13 12 21 17  8 20
  7]


In [11]:
arr=np.random.randint(1,10,[3,3])
arr

array([[9, 7, 6],
       [2, 2, 4],
       [3, 9, 5]])

In [12]:
print(arr.T)

[[9 2 3]
 [7 2 9]
 [6 4 5]]


In [13]:
print(np.transpose(arr))

[[9 2 3]
 [7 2 9]
 [6 4 5]]


In [14]:
print(arr.transpose())

[[9 2 3]
 [7 2 9]
 [6 4 5]]


In [15]:
arr=np.array([[2,4,6]])
arr

array([[2, 4, 6]])

In [16]:
np.swapaxes(arr,0,1)

array([[2],
       [4],
       [6]])

In [19]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
np.swapaxes(arr,0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [21]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
arr.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
arr.resize((2,6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr=np.array([1,2,3])

In [29]:
arr1=np.append(arr,4)
print(arr1)

[1 2 3 4]


In [30]:
arr2=np.append(arr,[4,5,6])
print(arr2)

[1 2 3 4 5 6]


In [31]:
arr3=np.insert(arr,0,[1,2,3])
print(arr3)

[1 2 3 1 2 3]


In [32]:
arr4=np.delete(arr,0)
print(arr4)

[2 3]


In [33]:
arr4=np.delete(arr,[0,2])
print(arr4)

[2]


In [34]:
arr=np.array([1,2,3])

In [35]:
arr1=np.copy(arr)
arr1=arr.copy()
arr1=np.array(arr,copy=True)

In [36]:
print(arr1)

[1 2 3]


In [37]:
arr=np.array([[1,2,3,4],[1,2,3,4]])
arr1=np.array([[5,6,7,8],[5,6,7,8]])

In [38]:
arr1

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [39]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [42]:
cat=np.concatenate((arr,arr1),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [43]:
cat=np.concatenate((arr,arr1),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [44]:
cat=np.vstack((arr,arr1))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [45]:
cat=np.r_[arr,arr1]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [46]:
cat=np.hstack((arr,arr1))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [47]:
cat=np.c_[arr,arr1]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [50]:
arr=np.random.rand(6,6)
print(arr)

[[0.25024789 0.38965115 0.68179003 0.88116174 0.60647949 0.50782094]
 [0.07491267 0.64096382 0.4757542  0.08495754 0.68963363 0.36275215]
 [0.21939145 0.33251652 0.40143336 0.75191783 0.98460089 0.01155985]
 [0.75707807 0.87745887 0.28591655 0.56029518 0.50496923 0.56727601]
 [0.8710138  0.11504418 0.3710532  0.96469314 0.43361694 0.62202442]
 [0.83320108 0.11546957 0.67281767 0.86172839 0.13736856 0.13354404]]


In [49]:
arr1=np.vsplit(arr,2)
print(arr1)

[array([[0.51141967, 0.82777927, 0.85928233, 0.22830637, 0.96632959,
        0.27486745],
       [0.6474321 , 0.16045264, 0.91968328, 0.96686232, 0.09210077,
        0.03610412],
       [0.11277325, 0.82580781, 0.92951204, 0.05716159, 0.89348681,
        0.47661447]]), array([[0.08809537, 0.14090511, 0.13019746, 0.85659319, 0.1644418 ,
        0.66057511],
       [0.2162968 , 0.41006285, 0.28682282, 0.041194  , 0.50742552,
        0.62234704],
       [0.40868422, 0.53582135, 0.43996162, 0.84149345, 0.67152241,
        0.45292773]])]


In [51]:
arr2=np.hsplit(arr,2)
print(arr2)

[array([[0.25024789, 0.38965115, 0.68179003],
       [0.07491267, 0.64096382, 0.4757542 ],
       [0.21939145, 0.33251652, 0.40143336],
       [0.75707807, 0.87745887, 0.28591655],
       [0.8710138 , 0.11504418, 0.3710532 ],
       [0.83320108, 0.11546957, 0.67281767]]), array([[0.88116174, 0.60647949, 0.50782094],
       [0.08495754, 0.68963363, 0.36275215],
       [0.75191783, 0.98460089, 0.01155985],
       [0.56029518, 0.50496923, 0.56727601],
       [0.96469314, 0.43361694, 0.62202442],
       [0.86172839, 0.13736856, 0.13354404]])]
