In [2]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [12]:
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
arr=np.array([[1,2,3],[4,5,6]],dtype='int')
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [22]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr,arr.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] int32


In [28]:
arr=np.arange(0,50,3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [33]:
arr=np.linspace(0,20,30)
print(arr,arr.size)

[ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.31034483 20.        ] 30


In [45]:
arr=np.random.rand(5,5)
print(arr,arr.size)

[[0.46510065 0.47647658 0.46551683 0.50469113 0.23707322]
 [0.68190873 0.29444908 0.45845621 0.75316898 0.32766788]
 [0.0918075  0.19272818 0.48050017 0.73722132 0.78071192]
 [0.37575737 0.95979711 0.70123744 0.64680229 0.22671756]
 [0.85380648 0.30226438 0.80760972 0.5237955  0.67747041]] 25


In [58]:
arr=np.random.randint(0,100,(3,3))
print(arr)

[[49  8 61]
 [86 76 81]
 [20  4  2]]


In [48]:
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [51]:
arr=np.nonzero((5,5))
print(arr)

(array([0, 1], dtype=int64),)


In [54]:
zeros=np.zeros_like(arr)
print(zeros,zeros.dtype)


[[0 0 0]
 [0 0 0]
 [0 0 0]] int32


In [55]:
arr=np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
empty=np.empty((5,5))
print(empty)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
empty=np.empty_like(arr)
print(empty,empty.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]] int32


In [60]:
full=np.full((4,4),10)
print(full)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [65]:
random=np.random.random(5)
print(random)

[0.24633658 0.59116047 0.81957953 0.50637184 0.19345211]


In [69]:
arr=[[0,1,2],[3,4,5]]
print(np.repeat(arr,5))

[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]


In [70]:
arr=[[0,1,2],[3,4,5]]
print(np.repeat(arr,5,axis=1))

[[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
 [3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]]


In [72]:
arr=[[0,1,2],[3,4,5]]
print(np.tile(arr,(5,5)))

[[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]]


In [74]:
identity_matrix=np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [76]:
identity_matrix=np.eye(5,k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [78]:
arr=np.random.rand(5,5)
print(arr,np.diag(arr))

[[0.10284188 0.40433426 0.0542784  0.20773917 0.25800895]
 [0.96088679 0.91124803 0.67571033 0.76540911 0.64844152]
 [0.93401943 0.77772076 0.57017166 0.74664448 0.76287639]
 [0.60457819 0.89052808 0.20974833 0.5217384  0.53961026]
 [0.40440425 0.09494149 0.06375295 0.49933565 0.59841592]] [0.10284188 0.91124803 0.57017166 0.5217384  0.59841592]


In [80]:
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [81]:
l1=[3,6,7,5]
l2=[4,5,1,7]
product=list(map(lambda x,y:x*y,l1,l2))
print(product)

[12, 30, 7, 35]


In [85]:
a1=np.array(l1)
a2=np.array(l2)
a3=a1*a2
print(a3)

[12 30  7 35]


In [86]:
ls=[i**2 for i in l1]
print(ls)

[9, 36, 49, 25]


In [91]:
asq=a1**2
print(asq)

[ 9 36 49 25]


In [93]:
l1=[i for i in range(10000000)]
l2=[j**2 for j in range(10000000)]
import time
t0=time.time()
product=list(map(lambda x,y:x*y,l1,l2))
t1=time.time()
lt=t1-t0
print("time taken",t1-t0)

time taken 3.2963626384735107


In [95]:
a1=np.array(l1)
a2=np.array(l2)
t0=time.time()
a3=a1*a2
t1=time.time()
nt=t1-t0
print("time taken",t1-t0)

time taken 0.0960087776184082


In [96]:
print("the ratio of time taken is {}".format(lt/nt))

the ratio of time taken is 34.333971541384194
