In [1]:
import numpy as np

In [2]:
arr=np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [3]:
arr=np.array([1,1,2,2,3,3,4,5,6])
uniques,counts=np.unique(arr,return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [4]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])

print(np.intersect1d(arr1,arr2))

[3 4 5]


In [5]:
print(np.union1d(arr1,arr2))

[1 2 3 4 5 6 7]


In [6]:
print(np.in1d(arr1,arr2))

[False False  True  True  True]


In [7]:
print(np.isin(arr1,arr2))

[False False  True  True  True]


In [8]:
print(np.setdiff1d(arr1,arr2))

[1 2]


In [9]:
print(np.setxor1d(arr1,arr2))

[1 2 6 7]


In [13]:
arr1=np.random.rand(5,5)
arr2=np.random.rand(5,5)
print(arr1)
print(arr2)

[[0.37557548 0.60755363 0.7065072  0.41703573 0.53447388]
 [0.11923345 0.99428844 0.01236094 0.42637461 0.78294097]
 [0.23403699 0.76070948 0.80613961 0.79466468 0.76548607]
 [0.95630842 0.90243497 0.4943685  0.21447014 0.6068229 ]
 [0.68708484 0.36983395 0.44200371 0.24870475 0.80025019]]
[[0.09470371 0.88954175 0.62825541 0.52816437 0.31263423]
 [0.85589153 0.48125562 0.90407357 0.68570842 0.60077807]
 [0.30185826 0.06911906 0.0952749  0.11416513 0.64649206]
 [0.16565867 0.11308715 0.78631494 0.43451139 0.18999708]
 [0.30490422 0.42849818 0.12176108 0.74562844 0.03213944]]


In [14]:
print(arr1.dot(arr2))

[[1.00088235 0.95149425 1.24554245 1.27535441 1.03558721]
 [1.17538081 0.96913067 1.40559311 1.51522568 0.74878761]
 [1.28163189 1.04787675 1.62964033 1.65332697 1.22693467]
 [1.23273332 1.60342478 1.70630294 1.72598907 1.22099484]
 [0.80022945 1.19075726 1.10113331 1.37170774 0.79571902]]


In [15]:
print(np.dot(arr1,arr2))

[[1.00088235 0.95149425 1.24554245 1.27535441 1.03558721]
 [1.17538081 0.96913067 1.40559311 1.51522568 0.74878761]
 [1.28163189 1.04787675 1.62964033 1.65332697 1.22693467]
 [1.23273332 1.60342478 1.70630294 1.72598907 1.22099484]
 [0.80022945 1.19075726 1.10113331 1.37170774 0.79571902]]


In [16]:
print(arr1@arr2)

[[1.00088235 0.95149425 1.24554245 1.27535441 1.03558721]
 [1.17538081 0.96913067 1.40559311 1.51522568 0.74878761]
 [1.28163189 1.04787675 1.62964033 1.65332697 1.22693467]
 [1.23273332 1.60342478 1.70630294 1.72598907 1.22099484]
 [0.80022945 1.19075726 1.10113331 1.37170774 0.79571902]]


In [17]:
arr=np.random.rand(5,5)
q,r=np.linalg.qr(arr)
print(q)
print(r)

[[-0.3942341  -0.53675613  0.65955574  0.06084125 -0.34315725]
 [-0.30793622 -0.62043169 -0.4862734  -0.43090771  0.31320365]
 [-0.54824117  0.04375756 -0.41255039  0.71866506 -0.10411342]
 [-0.45749425  0.44140999 -0.14384147 -0.53615812 -0.53637705]
 [-0.48978096  0.36083219  0.37099355 -0.08168165  0.69685482]]
[[-1.61444932 -0.74635956 -0.99750604 -1.13003586 -1.75608235]
 [ 0.         -0.66049086 -0.19913456 -0.73876219 -0.5875674 ]
 [ 0.          0.         -0.38743984 -0.19972425 -0.17097734]
 [ 0.          0.          0.          0.12938944 -0.10528116]
 [ 0.          0.          0.          0.         -0.13255887]]


In [18]:
arr=np.random.rand(5,5)
u,s,v=np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.51274774  0.37118517 -0.2374455  -0.37167327  0.63623104]
 [-0.33249582 -0.83177975 -0.40611287 -0.17678458 -0.03753031]
 [-0.44384683 -0.21338265  0.49151429  0.64074802  0.32453585]
 [-0.51047454  0.07677643  0.50404633 -0.44672903 -0.52904782]
 [-0.41103773  0.34487279 -0.53201783  0.46955441 -0.45671262]]
[2.60975401 1.05755937 0.49613109 0.39665101 0.03701317]
[[-0.60876718 -0.33196611 -0.25138444 -0.60457377 -0.30082794]
 [ 0.32595513 -0.24649521 -0.54030894  0.3529236  -0.64537163]
 [ 0.20035549  0.79711761 -0.35555602 -0.42337021 -0.13710862]
 [-0.26082949  0.31156739  0.60450936  0.17042091 -0.66364063]
 [ 0.64419052 -0.31075375  0.39117829 -0.54922662 -0.18379432]]


In [19]:
arr=np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.35449591+0.j         -0.29768989+0.37526267j -0.29768989-0.37526267j
 -0.07403993+0.j          0.57380473+0.j        ]


In [20]:
arr=np.random.rand(5,5)
w,v=np.linalg.eig(arr)
print(w)
print(v)

[ 2.93651534+0.j         -0.21811852+0.44702634j -0.21811852-0.44702634j
  0.1810666 +0.31927515j  0.1810666 -0.31927515j]
[[ 0.50631568+0.j         -0.42924386-0.26695687j -0.42924386+0.26695687j
  -0.04613364-0.01599047j -0.04613364+0.01599047j]
 [ 0.49833731+0.j         -0.29600941+0.21685027j -0.29600941-0.21685027j
  -0.36298279-0.37885115j -0.36298279+0.37885115j]
 [ 0.47807656+0.j         -0.15889306+0.36351084j -0.15889306-0.36351084j
   0.09932517+0.52943158j  0.09932517-0.52943158j]
 [ 0.31513719+0.j          0.5173347 +0.j          0.5173347 -0.j
   0.59962875+0.j          0.59962875-0.j        ]
 [ 0.40918908+0.j          0.27089879-0.33381079j  0.27089879+0.33381079j
  -0.25647445+0.08266934j -0.25647445-0.08266934j]]


In [21]:
print(np.trace(arr))

2.862411509098628


In [22]:
print(np.linalg.det(arr))

0.09787777581713147


In [27]:
arr=np.random.rand(5,5)
print(arr)

[[0.97331066 0.48365876 0.77144708 0.53949496 0.77580422]
 [0.70069521 0.46218382 0.84700139 0.14966419 0.84527331]
 [0.37413027 0.10957117 0.54419288 0.98384971 0.67075699]
 [0.23874847 0.92929445 0.62807172 0.1138353  0.41706461]
 [0.24850038 0.87195636 0.22595895 0.51919314 0.51783379]]


In [28]:
print(np.linalg.inv(arr))

[[ 2.27537638 -0.98904413 -1.02967358 -0.56753291 -0.00362152]
 [ 0.30203076 -0.61025432 -0.5052631   0.64589116  0.67791127]
 [ 0.04118092 -0.55085126  0.98394468  2.23747465 -2.23911175]
 [ 0.57431905 -1.38815031  0.93474816  0.40358483 -0.13035563]
 [-2.1942895   3.13436649 -0.02163686 -2.19621178  1.89909972]]


In [29]:
print(np.linalg.pinv(arr))

[[ 2.27537638 -0.98904413 -1.02967358 -0.56753291 -0.00362152]
 [ 0.30203076 -0.61025432 -0.5052631   0.64589116  0.67791127]
 [ 0.04118092 -0.55085126  0.98394468  2.23747465 -2.23911175]
 [ 0.57431905 -1.38815031  0.93474816  0.40358483 -0.13035563]
 [-2.1942895   3.13436649 -0.02163686 -2.19621178  1.89909972]]


In [30]:
y=[1,2,3,4,5]
print(np.linalg.solve(arr,y))

[-5.07997187  3.53885383 -0.35434773  1.5648241   4.72018435]


In [31]:
y=[1,2,3,4,5]
solution,residuals,rank,singular=np.linalg.lstsq(arr,y,rcond=-1)
print(solution)
print(residuals)
print(rank)
print(singular)

[-5.07997187  3.53885383 -0.35434773  1.5648241   4.72018435]
[]
5
[2.84562927 0.91896052 0.73577862 0.30521202 0.17429686]
