In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(arr[2])

2


In [4]:
print(arr[[2,5,6]])

[2 5 6]


In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(arr[2:])

[2 3 4 5 6 7 8 9]


In [9]:
print(arr[:3])

[0 1 2]


In [10]:
print(arr[2:7])

[2 3 4 5 6]


In [11]:
print(arr[0::2])

[0 2 4 6 8]


In [13]:
print(arr[-1])

9


In [14]:
for i in arr:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [15]:
arr=np.array([[2,5,7,5],[4,6,8,10],[10,12,15,19]])
print(arr)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [17]:
print(arr[2,3])

19


In [18]:
print(arr[1,:1])
print(type(arr[1,:1]))

[4]
<class 'numpy.ndarray'>


In [19]:
print(arr[:,2])

[ 7  8 15]


In [20]:
print(arr[:,:])

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [21]:
print(arr[:,:3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


In [22]:
print(arr[:2,:])

[[ 2  5  7  5]
 [ 4  6  8 10]]


In [23]:
print(arr[...,:3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


In [24]:
print(arr[:2,...])

[[ 2  5  7  5]
 [ 4  6  8 10]]


In [25]:
for row in arr:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [29]:
arr=np.arange(24).reshape(2,3,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
for row in arr:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
arr=np.arange(25).reshape((5,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
bools=np.array([True,True,False,True,False])
print(arr[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [39]:
print(arr[~bools])

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [40]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
print(arr[arr>5])

[ 6  7  8  9 10 11 12 13 14 15]


In [42]:
print(np.where(arr>5,-1,10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [43]:
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
