# ***NUMPY TUTORIAL***

In [1]:
import numpy as np


In [2]:
myarr=np.array([[3,6,32,7]],np.int64)

In [3]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr[0,1]

6

In [6]:
myarr[0,1]=45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

In [8]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.shape


(3, 3)

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.size

9

In [14]:
listarray[0,2]=45

In [15]:
listarray


array([[ 1,  2, 45],
       [ 5,  8,  5],
       [ 0,  3,  1]])

In [17]:
zeros=np.zeros((3,6))

In [18]:
zeros


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.size

18

In [22]:
rng=np.arange(20)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
lspace=np.linspace(1,50,15)

In [25]:
lspace

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [26]:
emp=np.empty((4,6))

In [27]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.11394918e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        1.11261162e-306, 8.34443015e-308, 8.34402698e-308]])

In [28]:
emp_like=np.empty_like(lspace)

In [29]:
emp_like

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [30]:
ide=np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [40]:
arr=np.arange(99)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr=arr.reshape(3, 33)

In [44]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr=arr.ravel()

In [47]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [49]:
ar=np.array(x)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ar.sum(axis=0)

array([12, 15, 18])

In [53]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [54]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
ar.flat

In [57]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [58]:
for i in ar:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [59]:
ar.ndim

2

In [60]:
ar.size

9

In [61]:
ar.nbytes

36

In [62]:
one=np.array([1,34,545,57,876])

In [63]:
one

array([  1,  34, 545,  57, 876])

In [64]:
one.argmax()

4

In [65]:
one.argmin()

0

In [66]:
one.argsort()

array([0, 1, 3, 2, 4], dtype=int64)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [74]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [77]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [78]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [85]:
ar2=np.array([[4,5,7],
       [5, 2, 8],
       [1, 6, 3]])

In [86]:
ar2

array([[4, 5, 7],
       [5, 2, 8],
       [1, 6, 3]])

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
ar+ar2

array([[ 5,  7, 10],
       [ 9,  7, 14],
       [ 8, 14, 12]])

In [89]:
ar*ar2

array([[ 4, 10, 21],
       [20, 10, 48],
       [ 7, 48, 27]])

In [90]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [91]:
ar.sum()

45

In [92]:
ar.max()

9

In [93]:
ar.min()

1

In [94]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
type(np.where(ar>5))

TypeError: 'tuple' object is not callable

In [101]:
np.count_nonzero(ar)

9

In [102]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [105]:
ar[2,1]=1

In [106]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 1]])

In [107]:
ar[2,2]=0

In [108]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [110]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [114]:
import sys

In [115]:
py_ar=[0,4,55,2]

In [116]:
np_ar=np.array(py_ar)

In [117]:
sys.getsizeof(1)*len(py_ar)

112

In [118]:
np_ar.itemsize*np_ar.size

16