# ***NUMPY TUTORIAL***

In [1]:
import numpy as np


In [2]:
myarr=np.array([[3,6,32,7]],np.int64)

In [3]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr[0,1]

6

In [6]:
myarr[0,1]=45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

In [8]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [2]:
listarray

NameError: name 'listarray' is not defined

In [10]:
listarray.shape


(3, 3)

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.size

9

In [14]:
listarray[0,2]=45

In [15]:
listarray


array([[ 1,  2, 45],
       [ 5,  8,  5],
       [ 0,  3,  1]])

In [17]:
zeros=np.zeros((3,6))

In [18]:
zeros


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.size

18

In [22]:
rng=np.arange(20)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
lspace=np.linspace(1,50,15)

In [25]:
lspace

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])