In [1]:
import numpy as np


In [3]:
arr=np.array([[1,2,3],[4,5,6]],dtype=np.int64)
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [4]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x240ea4997a0
byteorder:  little
byteswap:  False
type: int64
None


In [5]:
print(arr.dtype)

int64


In [6]:
print(arr.shape)

(2, 3)


In [7]:
print(len(arr))

2


In [8]:
print(arr.size)

6


In [9]:
print(arr.itemsize)

8


In [10]:
print(arr.nbytes)

48


In [11]:
print(np.random.rand())

0.15866639861116805


In [12]:
print(np.random.rand(3))

[0.2068728  0.32794723 0.78259505]


In [13]:
print(np.random.rand(3,3))

[[0.54586934 0.67201499 0.76849095]
 [0.65987336 0.56057003 0.04576653]
 [0.04871478 0.26975153 0.58058711]]


In [14]:
print(np.random.randn(3,3))

[[-1.35925713  0.50357803  0.47147504]
 [ 0.34601224  0.96519447 -0.74001622]
 [ 1.46778687  0.86155356 -0.1473053 ]]


In [15]:
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.70900275 0.84705182 0.82680001 0.69322765 0.43965707 0.16512868
 0.45982348 0.74344631 0.69544814 0.61241399]
[0.27340019 0.22443224 0.57602071 0.36350429 0.60965622 0.15893227
 0.9249135  0.57302895 0.52390811 0.00449797]
[0.0041373  0.92095083 0.09934172 0.04928239 0.13575973 0.25417391
 0.39390428 0.72938671 0.59093611 0.36530836]
[0.60750271 0.82518399 0.28513431 0.73984224 0.2187622  0.56932536
 0.17253083 0.46945312 0.60520068 0.39043204]


In [16]:
print(np.random.choice(range(3),10,replace=True,p=[0.1,0.8,0.1]))


[1 1 2 1 1 1 1 0 0 0]


In [18]:
print(np.random.choice(5,10))

[2 4 4 0 3 0 2 4 1 1]


In [19]:
print(np.random.choice([1,2,3],10))

[2 3 2 1 2 1 2 1 3 2]


In [20]:
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
np.random.shuffle(arr)
print(arr)

[5 6 7 8 2 0 9 4 3 1]


In [22]:
arr=np.array(range(10))
print('The initial array:',arr)
print('A permutation of the array:',np.random.permutation(arr))

The initial array: [0 1 2 3 4 5 6 7 8 9]
A permutation of the array: [5 1 7 9 2 0 3 4 8 6]
