In [1]:
import numpy as np

In [2]:
arr=np.random.randint(10,99,[3,3])
arr

array([[71, 80, 55],
       [90, 60, 58],
       [78, 57, 33]])

In [3]:
print(arr+10)
print(arr-10)
print(arr*10)
print(arr/10)


[[ 81  90  65]
 [100  70  68]
 [ 88  67  43]]
[[61 70 45]
 [80 50 48]
 [68 47 23]]
[[710 800 550]
 [900 600 580]
 [780 570 330]]
[[7.1 8.  5.5]
 [9.  6.  5.8]
 [7.8 5.7 3.3]]


In [4]:
arr1=np.array([1,2,3])
np.add(arr1,[8,9,10],out=arr1)
print(arr1)
np.subtract(arr1,[8,9,10],out=arr1)
print(arr1)
np.multiply(arr1,[1,2,3],out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(np.exp(arr))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [13]:
print(np.log(arr))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [14]:
print(np.log2(arr))

[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.80735492 3.         3.169925  ]]


In [15]:
print(np.log10(arr))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


In [16]:
print(np.sqrt(arr))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [17]:
print(np.sin(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [18]:
print(np.cos(arr))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print(np.sum(arr,axis=0))

[12 15 18]


In [21]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [22]:
print(np.min(arr,axis=0))

[1 2 3]


In [23]:
print(np.min(arr,axis=1))

[1 4 7]


In [24]:
print(np.max(arr,axis=0))

[7 8 9]


In [25]:
print(np.max(arr,axis=1))

[3 6 9]


In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(np.max(arr))
print(np.min(arr))

9
1


In [28]:
print(np.argmin(arr,axis=0))
print(np.argmax(arr,axis=0))

[0 0 0]
[2 2 2]


In [29]:
print(np.argmin(arr,axis=1))
print(np.argmax(arr,axis=1))

[0 0 0]
[2 2 2]


In [30]:
print(np.argmin(arr))
print(np.argmax(arr))

0
8


In [31]:
arr1=np.array([1,3,5,7,9])
arr2=np.array([0,4,3,8,7])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))

[1 4 5 8 9]
[0 3 3 7 7]


In [35]:
arr1=np.random.rand(10) * 10,intg=np.modf(arr1)
print('fractional:',re)
print('integral:',intg)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3744873191.py, line 1)

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
print(np.mean(arr))

5.0


In [38]:
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

[4. 5. 6.]
[2. 5. 8.]


In [39]:
print(np.median(arr))

5.0


In [40]:
print(np.median(arr,axis=0))
print(np.median(arr,axis=1))

[4. 5. 6.]
[2. 5. 8.]


In [41]:
arr1=np.random.rand(100)
print(np.percentile(arr1,[5,65,95]))

[0.05626912 0.65281086 0.96584699]


In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(np.std(arr))

2.581988897471611


In [44]:
print(np.std(arr,axis=0))
print(np.std(arr,axis=1))

[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [45]:
print(np.var(arr))

6.666666666666667


In [46]:
arr=np.random.rand(5,8)
arr

array([[0.43435406, 0.42818764, 0.69915471, 0.74202637, 0.43936429,
        0.91657328, 0.26558926, 0.16760671],
       [0.8406483 , 0.69102948, 0.35858847, 0.60400011, 0.9958182 ,
        0.57557158, 0.59298787, 0.44115109],
       [0.27479011, 0.45228747, 0.03556792, 0.3287468 , 0.14301337,
        0.49422041, 0.24922034, 0.94611234],
       [0.68437341, 0.30874653, 0.96177151, 0.29452097, 0.14801003,
        0.93728901, 0.55161978, 0.34586894],
       [0.22569187, 0.58964951, 0.87433766, 0.69255687, 0.76039726,
        0.95011393, 0.64149138, 0.0532754 ]])

In [47]:
print(np.cov(arr))

[[ 0.06418167 -0.00752248 -0.02478604  0.04054378  0.05866011]
 [-0.00752248  0.04225854 -0.01672114 -0.03141796 -0.00213112]
 [-0.02478604 -0.01672114  0.07752389 -0.01985922 -0.05339122]
 [ 0.04054378 -0.03141796 -0.01985922  0.09440371  0.0320063 ]
 [ 0.05866011 -0.00213112 -0.05339122  0.0320063   0.09613693]]


In [48]:
print(np.corrcoef(arr[:,0],arr[:,1]))

[[1.         0.12994075]
 [0.12994075 1.        ]]


In [49]:
print(np.cumsum(arr,axis=0))
print(np.cumsum(arr,axis=1))

[[0.43435406 0.42818764 0.69915471 0.74202637 0.43936429 0.91657328
  0.26558926 0.16760671]
 [1.27500236 1.11921712 1.05774318 1.34602648 1.4351825  1.49214487
  0.85857713 0.6087578 ]
 [1.54979247 1.57150459 1.09331111 1.67477328 1.57819587 1.98636527
  1.10779748 1.55487014]
 [2.23416588 1.88025112 2.05508261 1.96929425 1.7262059  2.92365428
  1.65941726 1.90073908]
 [2.45985775 2.46990064 2.92942027 2.66185112 2.48660316 3.87376821
  2.30090864 1.95401448]]
[[0.43435406 0.86254169 1.56169641 2.30372278 2.74308707 3.65966036
  3.92524962 4.09285633]
 [0.8406483  1.53167778 1.89026626 2.49426636 3.49008456 4.06565615
  4.65864401 5.09979511]
 [0.27479011 0.72707759 0.76264551 1.09139231 1.23440568 1.72862609
  1.97784644 2.92395878]
 [0.68437341 0.99311993 1.95489144 2.24941241 2.39742244 3.33471144
  3.88633123 4.23220017]
 [0.22569187 0.81534138 1.68967904 2.38223592 3.14263317 4.09274711
  4.73423848 4.78751388]]


In [50]:
print(np.cumprod(arr,axis=0))
print(np.cumprod(arr,axis=1))

[[0.43435406 0.42818764 0.69915471 0.74202637 0.43936429 0.91657328
  0.26558926 0.16760671]
 [0.365139   0.29589028 0.25070882 0.44818401 0.43752696 0.52755354
  0.15749121 0.07393988]
 [0.10033659 0.13382747 0.00891719 0.14733906 0.06257221 0.26072772
  0.03925001 0.06995544]
 [0.06866769 0.04131877 0.0085763  0.04339444 0.00926131 0.24437723
  0.02165108 0.02419541]
 [0.01549774 0.02436359 0.00749858 0.03005312 0.00704228 0.23218621
  0.01388898 0.00128902]]
[[4.34354056e-01 1.85985038e-01 1.30032315e-01 9.64874074e-02
  4.23931217e-02 3.88564027e-02 1.03198434e-02 1.72967499e-03]
 [8.40648301e-01 5.80912760e-01 2.08308619e-01 1.25818428e-01
  1.25292281e-01 7.21146765e-02 4.27631283e-02 1.88650008e-02]
 [2.74790115e-01 1.24284127e-01 4.42052797e-03 1.45323443e-03
  2.07831958e-04 1.02714795e-04 2.55986166e-05 2.42191671e-05]
 [6.84373408e-01 2.11297913e-01 2.03220312e-01 5.98526426e-02
  8.85879142e-03 8.30324781e-03 4.58023576e-03 1.58416128e-03]
 [2.25691868e-01 1.33079100e-01 1.

In [51]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])

In [52]:
print(arr1==arr2)
print(arr1<3)

[False False  True False False]
[ True  True False False False]
